export enum AssetClass {
  EQUITY = 'EQ',
  FIXED_INCOME = 'FI',
  MUTUAL_FUND = 'MP',
  LIFE_INSURANCE = 'LI',
  COMMODITY = 'CM',
  REAL_ESTATE = 'RE',
}

export enum TimePeriod {
  THIS_MONTH = 'THIS_MONTH',
  THIS_QUARTER = 'THIS_QUARTER',
  YTD = 'YTD',
  CUSTOM = 'CUSTOM',
}

export const ERROR_CODES = {
  UNAUTHORIZED: 'AUTH_001',
  FORBIDDEN: 'AUTH_002',
  TOKEN_EXPIRED: 'AUTH_003',
  INVALID_INPUT: 'INPUT_001',
  NOT_FOUND: 'DATA_001',
  RATE_LIMITED: 'RATE_001',
  INTERNAL_ERROR: 'SYS_001',
  SERVICE_UNAVAILABLE: 'SYS_002',
  AGENT_ERROR: 'AGENT_001',
  AGENT_TIMEOUT: 'AGENT_002',
} as const;
