/**
 * Canonical identity object returned after a successful SSO token validation.
 *
 * All fields are populated from the SSO provider (mock in S0-S3, real Nuvama
 * SSO in S4). The session_id and token_expires fields are generated by the
 * auth-service at validation time.
 */
export interface RMIdentity {
  rm_id: string;
  rm_name: string;
  rm_code: string;
  rm_email: string;
  rm_branch: string;
  rm_region: string;
  role: 'RM' | 'BM' | 'ADMIN';
  client_count: number;
  session_id: string;
  /** ISO 8601 — 24 hours from validation time */
  token_expires: string;
}

/**
 * Session data persisted to MongoDB and cached in Redis.
 */
export interface SessionData {
  session_id: string;
  rm_identity: RMIdentity;
  created_at: string;   // ISO 8601
  expires_at: string;   // ISO 8601
  status: 'active' | 'expired' | 'revoked';
}

/**
 * Raw token payload stored in MOCK_TOKENS map before session_id / expiry
 * fields are added.
 */
export interface MockTokenPayload {
  rm_id: string;
  rm_name: string;
  rm_code: string;
  rm_email: string;
  rm_branch: string;
  rm_region: string;
  role: 'RM' | 'BM' | 'ADMIN';
  client_count: number;
}
